### ISSUE TITLE
Social media removal

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/collections#33]
People use other tools to share web sites rather than links embedded these days? I say we bring bit.ly back and remove all others.

**Comment by sethjohnson1** [comment]
statistically no one uses them yet the cost of load time is significant - so worth doing.

**Comment by CenterNancy** [comment]
By "bringing bit.ly" back do you mean give them one bit.ly link that they can then share on whatever social media site they want?

**Comment by sethjohnson1** [comment]
part of other issue closing
