### ISSUE TITLE
Firewall issue?

### ISSUE THREAD

**Issue by CenterNancy** [sethjohnson1/collections#44]
Can anything easily be done to prevent the frequency of this error in the usergal controller?
![image](https://cloud.githubusercontent.com/assets/9464698/6093846/98ac4256-aece-11e4-9b99-6e2239bc7122.png)

**Comment by sethjohnson1** [comment]
i think this is resolved

**Comment by CenterNancy** [comment]
Ummm, me thinks, "Not so much..." I get the above maybe a third of the time. Could it be something other than the firewall?

**Comment by sethjohnson1** [comment]
Hmm... Hmm... I will think on it some more. I don't seem to have the
problem but I don't think I spend as much time with it as you do.

**Comment by CenterNancy** [comment]
It might be specific to rel - that's the one I'm in the most

Nancy

On May 15, 2015, at 5:50 AM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com>> wrote:

Hmm... Hmm... I will think on it some more. I don't seem to have the
problem but I don't think I spend as much time with it as you do.

On Thu, May 14, 2015 at 2:39 PM, CenterNancy <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Ummm, me thinks, "Not so much..." I get the above maybe a third of the
> time. Could it be something other than the firewall?
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/sethjohnson1/collections/issues/44#issuecomment-102163133>
> .
>

-

**Comment by sethjohnson1** [comment]
I had an epiphanous moment. Not sure if you can test it easily, but I think it will work more reliably now.

**Comment by CenterNancy** [comment]
So far so good! Entered 5 new relationships and browsed through pages, etc. with no problems. Thanks!

Nancy

**Comment by sethjohnson1** [comment]
ok good
