### ISSUE TITLE
social media login

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/collections#48]

**Comment by sethjohnson1** [comment]
awaiting final deployment and testing

**Comment by CenterNancy** [comment]
I see the note "explain something here?" on the login popup. Should we just say something like "Log-n to share, comment, interact!" Or is that lame?

**Comment by sethjohnson1** [comment]
No i like that, otherwise its not clear why to login.

**Comment by CenterNancy** [comment]
Yeah, and I thought that sounded positive instead of like we’re going to cyber-stalk them or something

Nancy

**Comment by sethjohnson1** [comment]
hahaha exactly - that's a given

**Comment by sethjohnson1** [comment]
closing this issue as final testing is on the rollout checklist
