### ISSUE TITLE
vGal page

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/collections#50]
needs lots of work, looks very bad - this page:

http://collections.centerofthewest.org/treasures/pack

**Comment by sethjohnson1** [comment]
lots of progress calling it good

**Comment by CenterNancy** [comment]
Hey Seth,

On the first frame of the virtual exhibits widget, could we change the text a little to shorten it up? I was thinking: “Explore these Virtual Exhibits. You can make your own!” Then could “Virtual Exhibits” in there be a link to http://collections.centerofthewest.org/usergals?

[cid:image001.png@01D09141.A20D3260]

Nancy

**Comment by sethjohnson1** [comment]
I made a massive amount of changes this weekend, just pulled them to zsj. I
did redo that section a bit, I can update the text as well.

**Comment by CenterNancy** [comment]
Oh – I love it. You did it with a title above and the “create your own…” below. Let’s keep it just like that! You must be an awfully productive insomniac ☺

Nancy
