### ISSUE TITLE
vgal index page

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/collections#51]
http://collections.centerofthewest.org/usergals

Make it look like attached image, and also from Nancy:

"One thing to think about... I like the idea of displaying the creator, but at this point many of them were made by Marguerite and myself so is that weird. Or could whatever algorithm you would use for sorting weight it toward others. I don't know."

edit - we will use the "featured" field to deal with default sorting

![virtual galleries idea](https://cloud.githubusercontent.com/assets/8754908/7658569/8257ebce-faf8-11e4-8e37-f0a2f3324887.jpg)

**Comment by sethjohnson1** [comment]
pending Nancy's feedback

**Comment by CenterNancy** [comment]
Wow, Seth - the whole rework for Online Collections is really beautiful; you've done an amazing job. Especially love the revamp of Virtual Galleries - not just the Index page, the tour of each exhibit starting with "Begin Tour >>" is great! The only thing I notice here is that the Comment section isn't lined up on the left justification line of the rest of the text.

**Comment by sethjohnson1** [comment]
thanks Nancy - yes that was the old, crappy comments section has been replaced with new
