### ISSUE TITLE
add feedback page

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/collections#56]
Also just get e-mail sorted out in general

**Comment by sethjohnson1** [comment]
I just put this at the end of About/Help so as not to clutter more menus. Think that's ok?

**Comment by CenterNancy** [comment]
Yes, that sounds good!

Nancy

On May 25, 2015, at 4:48 PM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com>> wrote:


I just put this at the end of About/Help so as not to clutter more menus. Think that's ok?

-

**Comment by CenterNancy** [comment]
I do like how the About pages looks now! And the feedback form goes well on that page.
