### ISSUE TITLE
consider where to put "search"

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/collections#57]
Really, it takes up a lot of space "above the fold" or whatever. Maybe it could be collapsed somehow.

**Comment by sethjohnson1** [comment]
Nancy check this out tomorrow and let me know if it's ok. Just used some anchor tags, nothing too fancy.

**Comment by CenterNancy** [comment]
So it takes you down to the results? I like it, but not sure it's obvious that's what the down arrow icon will do... Also, on my iPad and iPhone, the slideout menu isn't appearing now. Is that related to this? Or maybe that's issue #53?

**Comment by sethjohnson1** [comment]
yeah the slideout is broken, i am thinking of ditching it for a dropdown.
not sure what to do about the arrow, maybe it should say "browse". i dunno
or no arrow, i am open to any ideas
