### ISSUE TITLE
Laundry list for OC... (desktop)

### ISSUE THREAD

**Issue by CenterNancy** [sethjohnson1/collections#63]
Update, May 20:
6. I'm not seeing any of the Related Articles on phone or desktop. Tried to go back to an early one but no luck.
7. On iPhone, Virtual Gallery heading and image are a little too far left, so they run into edge of screen and are not lined up with the rest of the content.
8. On iPhone, without the footer menus, the band where they were is now blank but still appears. Looks kind of weird. Any way to remove it so just the copyright line appears without the band between it and the content?
For the About page, I'll click out the trucker hat to eliminate the remnants of the circle...

1. On the "Search Mediums", the "Jump to page" doesn't seem to work on results. It stays on page one even if you enter a higher page number. Works perfect on regular search. Not sure on Search Mediums as my test results never went to a second page.
2. In the "Browse Museums" links in Left Nav, only Buffalo Bill results in just that set checked under the search box; the rest all have all the museums checked.
3. On Log-in page, we need the link for people to use if they don't yet have an e-mail account. "If you need to create an account, register now&mdash;it's fast and free!" with words "register now" linked to the Register page.
4. We should probably also have the reverse on the "Register" page. "If you already have an account, log -in now! with the word "log-in" linked to the Log-in page.
5. On some pages, the text runs pretty close to the horizontal bottom line. Can we build in just a little bit of bottom margin? Example would be the About page.
Z. This one is so minor I'm giving it a "z" instead of a number: Our style for e-mail includes the hyphen; it's without it everywhere.

**Comment by CenterNancy** [comment]
I have updated the previous comment now.

**Comment by sethjohnson1** [comment]
Ok I did all that stuff except I am not sure about:
"On iPhone, Virtual Gallery heading and image are a little too far left, so they run into edge of screen and are not lined up with the rest of the content." I might have to see it on your phone, mine seems fine.
and maybe we can open another issue for the email fix - I can't do a find/replace all because lots of variables use "email" and it would screw those up. Also, style guide or not, "e-mail" is like "on-line" - sooooo 1984. If the NY Times dropped the hyphen, maybe we should too.

**Comment by CenterNancy** [comment]
Well, we can agree to disagree, I guess, on e-mail/email, as the basis of our style guide is the Chicago Manual of Style, not the NY Times ?

Nancy

On May 25, 2015, at 2:10 PM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok I did all that stuff except I am not sure about:
"On iPhone, Virtual Gallery heading and image are a little too far left, so they run into edge of screen and are not lined up with the rest of the content." I might have to see it on your phone, mine seems fine.
and maybe we can open another issue for the email fix - I can't do a find/replace all because lots of variables use "email" and it would screw those up. Also, style guide or not, "e-mail" is like "on-line" - sooooo 1984. If the NY Times dropped the hyphen, maybe we should too.

-

**Comment by sethjohnson1** [comment]
Haha, yes, I will change it as I see it, feel free to point them out.

**Comment by CenterNancy** [comment]
? Not a big deal

Nancy

On May 25, 2015, at 3:27 PM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com>> wrote:

Haha, yes, I will change it as I see it, feel free to point them out.

On Mon, May 25, 2015 at 3:01 PM, CenterNancy <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Well, we can agree to disagree, I guess, on e-mail/email, as the basis of
> our style guide is the Chicago Manual of Style, not the NY Times ?
>
> Nancy
>
> On May 25, 2015, at 2:10 PM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com>
> <mailto:notifications@github.com>> wrote:
>
>
> Ok I did all that stuff except I am not sure about:
> "On iPhone, Virtual Gallery heading and image are a little too far left,
> so they run into edge of screen and are not lined up with the rest of the
> content." I might have to see it on your phone, mine seems fine.
> and maybe we can open another issue for the email fix - I can't do a
> find/replace all because lots of variables use "email" and it would screw
> those up. Also, style guide or not, "e-mail" is like "on-line" - sooooo
> 1984. If the NY Times dropped the hyphen, maybe we should too.
>
> -
> Reply to this email directly or view it on GitHub<
> https://github.com/sethjohnson1/collections/issues/63#issuecomment-105304449
> >.
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/sethjohnson1/collections/issues/63#issuecomment-105313849>
> .
>

-

**Comment by sethjohnson1** [comment]
I think I already found the bulk of them :)

**Comment by CenterNancy** [comment]
![image](https://cloud.githubusercontent.com/assets/9464698/7802937/1b495954-02ff-11e5-8888-e18f9ac6697e.png)

**Comment by sethjohnson1** [comment]
Haha, very true - and I do like to follow rules every now and then. Anyway,
I pulled the changes from this weekend into zsj at work - so you can check
that out and let me know what other things I can fix up. It's getting
nearly ready - I didn't get to user-enabled tags yet but it shouldn't be
too bad. I don't really know where we could put them. Hopefully I will be
back Wednesday.

**Comment by CenterNancy** [comment]
Sounds good! Have a good extra day off.

Nancy

On May 25, 2015, at 5:37 PM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com>> wrote:

Haha, very true - and I do like to follow rules every now and then. Anyway,
I pulled the changes from this weekend into zsj at work - so you can check
that out and let me know what other things I can fix up. It's getting
nearly ready - I didn't get to user-enabled tags yet but it shouldn't be
too bad. I don't really know where we could put them. Hopefully I will be
back Wednesday.

On Mon, May 25, 2015 at 4:57 PM, CenterNancy <notifications@github.com<mailto:notifications@github.com>>
wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/9464698/7802937/1b495954-02ff-11e5-8888-e18f9ac6697e.png>
>
> -
> Reply to this email directly or view it on GitHub
> <https://github.com/sethjohnson1/collections/issues/63#issuecomment-105331920>
> .
>

-
