### ISSUE TITLE
Prompts for encouraging people to make virtual exhibits

### ISSUE THREAD

**Issue by CenterNancy** [sethjohnson1/collections#64]
Here's a random list of questions I've started...

What would you gather on the eve of the zombie apocalypse? -yours :)
What animals would you like to see in Yellowstone?
Make a virtual exhibit of places you saw in Yellowstone.
How many ways can a horse buck you off?
What are some languages that Wild West posters were printed in?
What would your costume look like if you were a Wild West performer?
What tools would you want if you were a working cowboy?
If you had your own art museum what artworks would you display?
What knives would you bring to a gun fight?
What games would you like to learn how to play?
If you were starting a zoo what animals would you choose?
How would you outfit your wagon for a transcontinental journey?
If you were an artist, how would you depict George Armstrong Custer?
What would you aim at if you were a trick shooter?
How would you furnish a house?
What would you include in your hardware store inventory?
If you were a realtor, what dwellings would you sell?
Someone says to you, “I see by your outfit that you are a cowboy/girl.” What clothes and accoutrements are you wearing?
What clothes and gear would you want if you were an Indian warrior?
Show through our collection objects what “the West” means to you?
What toys or objects would you choose to keep kids entertained?

**Comment by sethjohnson1** [comment]
Nancy - we could probably start this experiment on Facebook. One day, we'll just ask the question and then tell people to share back on FB (effectively having to do almost nothing for the site's code). I think we need a prize - do we have any Center of the West swag lying around? (10 free copies of Points West, and the webcam Amazon sent Seth by accident)

**Comment by sethjohnson1** [comment]
all right we're doing this
