### ISSUE TITLE
user tags

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/collections#65]
see if PL comes up with a lexicon, will build code base in anticipation

**Comment by sethjohnson1** [comment]
this idea was shelved and never fully thought out and the person that came up with it doesn't work here anymore.

**Comment by patricialord** [comment]
So, who does this originate from?  Now I am just curious.



Elizabeth Holmes
Administrative and Compliance Manager

O 307-578-4038
Buffalo Bill Center of the West
720 Sheridan Avenue, Cody, WY 82414
centerofthewest.org<http://centerofthewest.org/>

[Centennial-ribbon_email]

**Comment by CenterNancy** [comment]
Hi Liz – this is from Seth via our web-based repository – for source code management and version tracking of our various websites. Patricia was added as a commenter/contributor for the online collection when she worked here, so you must be getting her notifications now… Seth can probably delete her now and unsubscribe you from the notifications, right Seth?

Nancy
