### ISSUE TITLE
internal error and 404 pages

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/collections#76]
Will do some basic fixing, don't need to be too fancy

**Comment by sethjohnson1** [comment]
included error reporting capabilities. and this picture! http://collectionimages.s3-website-us-west-1.amazonaws.com/1/112.67.jpg

**Comment by CenterNancy** [comment]
Haha! ?

Nancy

On May 25, 2015, at 8:13 PM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com>> wrote:


included error reporting capabilities. and this picture! http://collectionimages.s3-website-us-west-1.amazonaws.com/1/112.67.jpg

-

**Comment by sethjohnson1** [comment]
It's hard to show in dev, so here is a screenshot of the main part, then if they click the link it goes to the page below, which is just a dynamically altered version of the feedback form with some data autofilled. Fairly simple, but let me know if you want the wording changed. Hopefully people don't see too many of these!

![404](https://cloud.githubusercontent.com/assets/8754908/7805050/d5fe33d6-0328-11e5-9d71-52922bfadaed.jpg)

**Comment by CenterNancy** [comment]
Just suggest this slight wording change:
If you keep receiving this message, please leave feedback at the bottom of this page.
Just follow the link and send information on this, or on anything else regarding our Online Collections.
