### ISSUE TITLE
museum icons are blurry

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/collections#81]
Do we have some "crispier" ones somewhere? These seem to have the strange feathered-edge thing and look blurry, esp. on mobile

**Comment by CenterNancy** [comment]
I'll check with Desiree tomorrow. I'm pretty sure she will cuz she does have a crisper main logo I've been meaning to forward...

Nancy

On May 28, 2015, at 5:02 PM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Do we have some "crispier" ones somewhere? These seem to have the strange feathered-edge thing and look blurry, esp. on mobile

-

**Comment by CenterNancy** [comment]
Desiree is going to put all the “crisper” logos and icons in the Public Graphics folder for us. Probably sometime today.

Nancy

**Comment by sethjohnson1** [comment]
Thank you. I had a chance to speak with her as well, apparently it's
something that happened during the conversion to png - the originals do not
have the border.

**Comment by CenterNancy** [comment]
Huh - siegel & gale did that I think (once again, money well spent...)

Nancy

On May 28, 2015, at 5:02 PM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com>> wrote:


Do we have some "crispier" ones somewhere? These seem to have the strange feathered-edge thing and look blurry, esp. on mobile

-

**Comment by sethjohnson1** [comment]
ah well that was slightly more complicated than expected - had to use SVG instead of PNG - but they look great
