### ISSUE TITLE
e-mail web when commented

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/collections#84]
send comment and profile info

**Comment by sethjohnson1** [comment]
should be working will check with Nancy

**Comment by CenterNancy** [comment]
Yep – it worked on the “not as cool trucker hat” comment. I replied to your comment so did you get a notice for that since you were the original commenter?

Nancy

**Comment by sethjohnson1** [comment]
Glad it worked. I opened a new issue of how we could notify people - I think that's a good idea.
