### ISSUE TITLE
Make usergal auto-associate with account if e-mail exists

### ISSUE THREAD

**Issue by sethjohnson1** [sethjohnson1/collections#95]
So if someone makes a usergal without logging in, but uses an existing e-mail. Not sure if this is a bad idea or not, but I like it for myself.

**Comment by CenterNancy** [comment]
Yes - I like it too; easier to contact them if we want to; and if we already have their e-mail it's not a privacy issue, right?

Nancy

On Feb 24, 2016, at 8:48 AM, sethjohnson1 <notifications@github.com<mailto:notifications@github.com>> wrote:


So if someone makes a usergal without logging in, but uses an existing e-mail. Not sure if this is a bad idea or not, but I like it for myself.

-

**Comment by sethjohnson1** [comment]
We decided not to do this because then anyone could make a gallery under your email
